export enum Category {
  Bakery = "BAKERY",
  Frozen = "FROZEN",
  FruitVeg = "FRUITVEG",
  Clothing = "CLOTHING",
  Tinned = "TINNED",
  Dairy = "DAIRY",
  Electrical = "ELECTRICAL",
  Cereal = "CEREAL",
  Sweets = "SWEETS",
  Pets = "PETS",
  Drinks = "DRINKS",
  Medicine = "MEDICINE",
  Bathroom = "BATHROOM",
  Books = "BOOKS",
}
